apiVersion: v1
kind: Service
metadata:
  name: subscription # Name of the Service
spec:
  type: LoadBalancer
  selector:
    app: subscription # Specify which Pod labels the service routes traffic to (match the deployment.yaml file's template.metadata.labels)
  ports:
  - port: 80
    targetPort: 9696 # The port defined in the containerPort of deployment.yaml
